version: '3.9'

services:
  slc_budget_app:
    container_name: slc_budget_app
    image: img-slc-app:1.0.0
    build: .
    ports:
      - 8080:8080
    environment:
      - DATABASE_URL=jdbc:postgresql://slc-budget.cwyblvgboiei.us-east-1.rds.amazonaws.com:5432/postgres
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=slc-budget1*